### ISSUE TITLE
Using DateTime scalar with a date-time string at UTC.

### ISSUE THREAD

**Issue by slorenzo** [okgrow/graphql-scalars#11]
Hi there! First at all, thanks for this contribution! It's really helful.

I have used this library over Apollo Server and Mongoose as a ORM. At some point, Mongoose converts the date fields to `String` and the DateTime doesn't catch this. I spent some hours dealing with this issue.

After investigating different approaches to make this, I figure out that DateTime scalar [doesn't accept](https://github.com/okgrow/graphql-scalars/blob/master/src/DateTime.js#L11) a date-time string at UTC.

Can someone help me to solve this? I found a possible solution [here](https://github.com/excitement-engineer/graphql-iso-date/blob/master/src/dateTime/index.js#L47) but I have used others scalars of this package.

Thanks in advance!

**Comment by ccuilla** [comment]
@slorenzo Thanks for bring this up. I'll need to look at it but probably won't have time until early/mid next week. If you'd like to submit a PR before then, we'd welcome the contribution.

**Comment by ccuilla** [comment]
@slorenzo Check out version 0.4.1.

**Comment by slorenzo** [comment]
It works using the new version. Thanks @ccuilla!
