### ISSUE TITLE
Update Documentation for Spread Syntax Option

### ISSUE THREAD

**Issue by Saeris** [okgrow/graphql-scalars#13]
Hey there! Ran into this issue following the given documentation and the option to use the default export of the library in my resolver map using the spread operator. The problem is that if you do that, your GraphQL server will complain at you for having three missing scalar types: `UnsignedInt`, `UnsignedFloat` and `RegularExpression`. These need to be added to the list of scalars that need to be added to the schema because the documentation isn't clear on this. Here's an updated list you can just copy over into the docs:

```graphql
scalar DateTime

scalar NonPositiveInt

scalar PositiveInt

scalar NonNegativeInt

scalar UnsignedInt

scalar NegativeInt

scalar NonPositiveFloat

scalar PositiveFloat

scalar NonNegativeFloat

scalar UnsignedFloat

scalar NegativeFloat

scalar EmailAddress

scalar URL

scalar PhoneNumber

scalar PostalCode

scalar RegularExpression
```

Additionally, I'd like to suggest a process for making this simpler: in my own project I have all of my definitions in separate `.gql` files, which I then export from a `index.js` file, which looks something like this:

```graphql
export { default as DateTime } from "./dateTime.gql"
// ... other exports ...
```

I then import this single index in my `schema.js` file where I use it like so:

```javascript
import { makeExecutableSchema } from "graphql-tools"
import OKGGraphQLScalars from '@okgrow/graphql-scalars'
import * as types from "./types"
import * as enums from "./types/enums"
import * as inputs from "./types/inputs"
import * as interfaces from "./types/interfaces"
import * as scalars from "./types/scalars"
import * as unions from "./types/unions"
import * as resolvers from "./resolvers"

export const schema = makeExecutableSchema({
  typeDefs: [
    ...Object.values(types),
    ...Object.values(enums),
    ...Object.values(inputs),
    ...Object.values(interfaces),
    ...Object.values(scalars),
    ...Object.values(unions)
  ],
  resolvers: { ...OKGGraphQLScalars, ...resolvers }
})
```

This helps to keep my schema modular and easy to manage. While this may be overkill to make individual files for each scalar definition, you could still do something similar where you export a single `OKGScalarDefinitions` file as a named export that people can use in a similar fashion as I have above. That way they can quickly add all of the custom scalars to their schema in one place in only three lines of code, and updates to this package such as adding new scalars/resolvers will stay in sync, whereas right now any additions will break servers where the spread technique is used.

**Comment by ccuilla** [comment]
Fixed in v0.4.2
