### ISSUE TITLE
Bug: URL Scalar doesn't support localhost, 0.0.0.0, etc

### ISSUE THREAD

**Issue by Saeris** [okgrow/graphql-scalars#15]
As the title says, the URL scalar will return null for URLs that contain `localhost`, `127.0.0.1:8000` or whatever variant thereof. While this likely wouldn't be a problem for production environments, it breaks local development when referencing locally served assets. The only solution I've found is to revert back to using `String`.

**Comment by RichardLitt** [comment]
That does sound like a bug. Want to add it to the other PR, or to make a new one?

**Comment by ccuilla** [comment]
@Saeris Quick update. I've started by writing some tests for these cases, and it looks like `127.0.0.1` and `127.0.0.1:3000` (as well as `0.0.0.0` and `0.0.0.0:3000`) pass. But `localhost` definitely doesn't.

I will try _my_ regex skills on this. :-)

**Comment by ccuilla** [comment]
@Saeris Fair enough on the bundle size point. I have a branch almost ready that fixes the localhost issue. But does not go further (e.g., data URIs). I'm open to another approach on this.

**Comment by Saeris** [comment]
I decided what was best for me going forward was to just publish and maintain my fork separately, since I'd like to add new scalars as per my own project's needs. You can check out my implementation here:

https://github.com/Saeris/graphql-scalars

Feel free to use whatever you'd like!

**Comment by ccuilla** [comment]
@Saeris That's totally cool! I'll check yours out from time-to-time. Thanks for the contribution and thanks for doing stuff that contributes back to the overall community! That's what we're all trying to do too.

**Comment by Saeris** [comment]
Yes please do! Since publishing last night I've added another 10 scalars and I have more in mind. As a side note, I was able to fix the commented out tests for all the number scalars. Seems with the Joi validation they now properly throw.

**Comment by ccuilla** [comment]
Fixed in v0.4.2
