### ISSUE TITLE
Scalar URL type doesn't support a lot of valid urls

### ISSUE THREAD

**Issue by igtm** [okgrow/graphql-scalars#17]
# What is the problem?
https://github.com/okgrow/graphql-scalars/blob/37ab0b82ae3810bf85a4a2dd60beb7883728d05b/src/URL.js#L6

I'd like to have image urls saved on S3 of which url should be like `https://s3.ap-northeast-1.amazonaws.com/hoge.fuga/foo.jpg`.
but got error like this

```
TypeError: Value is not a valid URL: https://s3.ap-northeast-1.amazonaws.com/hoge.fuga/foo.jpg`
```
[reproduction](https://jsfiddle.net/igtm11/bcy8th7p/)

# How can it be solved?

- use [this](https://github.com/chriso/validator.js/blob/6ce306093b33a7c22fdb6237802fd21cfbd6954e/src/lib/isURL.js#L34) library.

- choose one of [them](https://mathiasbynens.be/demo/url-regex) if you like regexp.

**Comment by RichardLitt** [comment]
Thanks for logging. It does sound like a better URL library would help. Thanks for the PR.
