### ISSUE TITLE
Could not find a declaration file for module '@okgrow/graphql-scalars'.

### ISSUE THREAD

**Issue by vdiaz1130** [okgrow/graphql-scalars#19]
Following steps in README gets me to a point where I get the following error

    [ts]
    Could not find a declaration file for module '@okgrow/graphql-scalars'.  '/Users/<user>/<appPath>/node_modules/@okgrow/graphql-scalars/index.js' implicitly has an 'any' type.
      Try `npm install @types/okgrow__graphql-scalars` if it exists or add a new declaration (.d.ts) file containing `declare module '@okgrow/graphql-scalars';` [7016]

I tried `npm install @types/okgrow__graphql-scalars` but get error Not Found- probably an oversight on my part but can't pin it down.

Any ideas?

**Comment by vkykv** [comment]
Looks like this project doesn't have type definitions.

I dropped this into my types folder (.d.ts) file as a quick fix

```
declare module '@okgrow/graphql-scalars' {
  import { GraphQLScalarType } from 'graphql';

  declare class EmailAddress extends GraphQLScalarType {};
  declare class DateTime extends GraphQLScalarType {};
  declare class NonPositiveInt extends GraphQLScalarType {};
  declare class PositiveInt extends GraphQLScalarType {};
  declare class NonNegativeInt extends GraphQLScalarType {};
  declare class NegativeInt extends GraphQLScalarType {};
  declare class NonPositiveFloat extends GraphQLScalarType {};
  declare class PositiveFloat extends GraphQLScalarType {};
  declare class NonNegativeFloat extends GraphQLScalarType {};
  declare class NegativeFloat extends GraphQLScalarType {};
  declare class EmailAddress extends GraphQLScalarType {};
  declare class URL extends GraphQLScalarType {};
  declare class PhoneNumber extends GraphQLScalarType {};
  declare class PostalCode extends GraphQLScalarType {};

  declare class RegularExpression extends GraphQLScalarType {
    constructor(name: string, regex: RegExp);
  };
}

```

**Comment by RichardLitt** [comment]
This might be worth adding. Am I right in thinking that there's no overhead to adding type definitions?
