### ISSUE TITLE
when I have input object type error, path printed in the error message is undefined

### ISSUE THREAD

**Issue by capaj** [okgrow/graphql-scalars#20]
I got this error on our prod this week:

```
Expected type EmailAddress at value[1].email; Value is not a valid email address: path: undefined
```
It works well for output objects and prints out the path in the object, but for input objects it prints undefined. Maybe just  omit it when it's undefined?

**Comment by capaj** [comment]
oh this error is raised somewhere else-I'll open this up in some other repo then

**Comment by RichardLitt** [comment]
Thanks for following up, @capaj. :)
