### ISSUE TITLE
GraphQL 14 is released

### ISSUE THREAD

**Issue by zefexdeveloper** [okgrow/graphql-scalars#25]
GraphQL 14 has been released but it's still asking for `"graphql": "^0.13.1"` in the peer dependencies

**Comment by ccuilla** [comment]
We'll fix this in v0.4.3 coming shortly.

**Comment by zefexdeveloper** [comment]
Thank you very much @ccuilla

**Comment by ccuilla** [comment]
Updated in v0.4.3.
