### ISSUE TITLE
What's your workflow for checking urls exist?

### ISSUE THREAD

**Issue by bebraw** [okgrow/graphql-scalars#27]
Do you have something external set up to make sure the urls actually exist? It's great to validate the shape but being able to tell they don't 404 would be better.

I imagine it's not that difficult to set up something to do this based on a schema. Just curious if you have solved this already somehow.

**Comment by ccuilla** [comment]
Do you meaning checking the URL at runtime against a 404?

**Comment by bebraw** [comment]
Yeah, something along the lines of that. I generate static sites from my
API so I guess I could try to do a check when building.

**Comment by ccuilla** [comment]
Okay. Hadn't considered doing that.

I'd welcome a PR to see what that might look like.

That said, I wonder if that idea steps outside the concept and philosophy of what GraphQL scalars are meant to be and do. I think they're primarily intended as _type_ and _format_ checking elements. So `URL` checks it to be a valid URL _format_ but not that it is an actual URL to a valid location. Same with the `EmailAddress` scalar.

I could be too limited in my thinking here though.

**Comment by ccuilla** [comment]
@bebraw After further thought on this, I think that having the URL scalar actually check to see if the URL is a live URL isn't really an appropriate function for a scalar. The purpose of scalars is merely to enforce the "type-ness" of a field. Whether the content is valid (e.g., the email address is an _actual_ email address) is beyond the scope of what scalars should do.

Thanks for using the package, and I hope it continues to be useful for you.

**Comment by bebraw** [comment]
Hi,

I agree. Likely the best place is actually a resolver or some other place.
