### ISSUE TITLE
Probleme with Email scalar

### ISSUE THREAD

**Issue by B2o5T** [okgrow/graphql-scalars#29]
Hi there i am getting than error for this email - Value is not a valid email address: clautilde.obanga@sometransports.fr

**Comment by ccuilla** [comment]
I'm looking into this. Obviously an issue with the regex we're using. If you happen to have a regex that you know does work, that would be great. Thanks.

**Comment by ccuilla** [comment]
I have tested the regex we're using:

`^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$`

here: https://regex101.com/r/7ZYRPT/1/ and the email address matches.

I also added a quick test to the test suite for that email address and it passes.

Can you create a re-production for this?

**Comment by B2o5T** [comment]
@ccuilla thanks, i found space character at the end
